---
- name: Reboot if required
  command: shutdown -r now
  args:
    removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true
  when: rebootvar == Yes

- name: Wait for machine to come back respond.
  wait_for_connection:
    delay: 5
    timeout: 300
    when: rebootvar == Yes
