---
- name: Check for active downloads
  find:
    paths: '/mnt/storage/MiscData/Downloads/inprog'
    pattern: '*.*'
    recurse: yes
  register: filesFound

- name: Reboot if required
  command: shutdown -r now
  when: filesFound < 1
  args:
    removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true

- name: Wait for machine to respond.
  wait_for_connection:
    delay: 5
    timeout: 300
