---
- hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Launch instance
    ec2:
      key_name: AWStest
      instance_type: t2.micro
      image: ami-09a7fe78668f1e2c0
      region: us-west-1
      wait: yes
      group: ['default', 'SSH']
      count: 1
      vpc_subnet_id: subnet-a0e332c6
      assign_public_ip: yes

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_dns_name }}"
    wait_for_connection:
      delay: 60
      timeout: 320
    loop: "{{ ec2.instances }}"