---
- hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Launch instance
    ec2:
      key_name: AWStest2
      instance_type: t2.micro
      image: ami-021bb9f371690f97a
      region: us-west-1
      wait: yes
      group: ['default', 'SSH', 'HTTPtest']
      count: 1
      vpc_subnet_id: subnet-a0e332c6
      assign_public_ip: yes
    register: ec2

  - name: Add new instance to host group
    add_host:
      name: "{{ item.public_ip }}"
      group: launched
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for: 
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 30
      timeout: 300
      state: started
    loop: "{{ ec2.instances }}"

- hosts: launched
  user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
  - name: Update the packages
    yum:
      name: "*"
      state: latest

  - name: Install packages for LAMP web server
    yum:
      name:
        - httpd24
        - php72
        - mysql57-server
        - php72-mysqlnd
      state: present

  - name: Start httpd service and ensure it starts up with each boot
    service:
      name: httpd
      state: started
      enabled: yes
  
  - name: Create a test file in /var/www
    shell: echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php

  - name: Check that web server returns status 200
    uri: 
      url: http://"{{ ansible_facts['nodename'] }}"/phpinfo.php