---
- hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Launch instance
    ec2:
      key_name: AWStest2
      instance_type: t2.micro
      image: ami-09a7fe78668f1e2c0
      region: us-west-1
      wait: yes
      group: ['default', 'SSH']
      count: 1
      vpc_subnet_id: subnet-a0e332c6
      assign_public_ip: yes
    register: ec2

  - name: Add new instance to host group
    add_host:
      name: "{{ item.public_ip }}"
      group: launched
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for: 
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 30
      timeout: 300
      state: started
    loop: "{{ ec2.instances }}"

- hosts: launched
  user: ec2-user
  become: yes
  become_method: sudo

- tasks:
  - name: Update the packages
    yum:
      name: "*"
      state: latest