---
- hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Launch instance
    ec2:
      key_name: AWStest2
      instance_type: t2.micro
      image: ami-021bb9f371690f97a
      region: us-west-1
      wait: yes
      group: ['default', 'SSH', 'HTTPtest']
      count: 1
      vpc_subnet_id: subnet-a0e332c6
      assign_public_ip: yes
    register: ec2

  - name: Add new instance to host group
    add_host:
      name: "{{ item.public_ip }}"
      group: launched
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for: 
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 30
      timeout: 300
      state: started
    loop: "{{ ec2.instances }}"

- hosts: launched
  user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Update the packages
    yum:
      name: "*"
      state: latest

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        region: us-west-1
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'