---
- hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Launch instance
    ec2:
      key_name: VanAWS
      instance_type: t2.micro
      image: ami-09a7fe78668f1e2c0
      region: us-west-1
      wait: yes
      group: test
      count: 1
      vpc_subnet_id: subnet-a0e332c6
      assign_public_ip: yes
