---
- hosts: Gandalf
  connection: local

  gather_facts: no
  become: true
  
  tasks:
    - block:
        - name: Run Apt Updates
          import_role:
            name: apt

        - name: Run SnapRAID Tasks
          import_role:
            name: snapraid
          when: arraysync == "Yes" or arrayscrub == "Yes"

        - name: Sync with S3 Bucket
          import_role:
            name: s3sync
          when: s3syncvar == "Yes"

        - name: Test the UPS
          import_role:
            name: upstest
          when: upstest == "Yes"

        - name: Reboot if necessary
          import_role:
            name: rebooter
          when: rebootvar == "Yes"

      rescue:
        - name: Send failure email
          mail:
            host: smtp.example.com
            port: 587
            username: your_user
            password: your_pass
            to: ops-team@example.com
            subject: "Ansible Playbook Failed"
            body: "One of the roles (apt, snapraid, s3sync, upstest, rebooter) failed."