---
- hosts: Gandalf

  gather_facts: no
  become: true
  
  roles:
   - apt
   - ups
   
  roles:
   - snapraid
  when: arraysync == "Yes" or arrayscrub == "Yes"
   
  roles:
   - rebooter
  when: rebootvar == "Yes"
