---
- hosts: Gandalf

  gather_facts: no
  become: true
  
  roles:
    - role: apt
    - role: ups
      when: upstest == "Yes"
    - role: snapraid
      when: arraysync == "Yes" or arrayscrub == "Yes"
    - role: rebooter
      when: rebootvar == "Yes"
