---
- name: Begin UPS test (don't freak out at the noise!)
  command: /usr/sbin/pwrstat -test

- name: Wait for test to finish
  wait_for:
    timeout: 60

- name: Print UPS status and last test results to file
  command: /usr/sbin/pwrstat -status > /home/van/ups_status.txt

- name: Slurp the file
  slurp:
    src: /home/van/ups_status.txt
  register: ups_status

- name: Mail the file
  mail:
    host: smtp.example.com
    port: 587
    username: your_user
    password: your_pass
    to: ops-team@example.com
    subject: "UPS Status"
    body: "{{ ups_status.content | b64decode }}"