---
- name: Begin UPS test (don't freak out at the noise!)
  command: /usr/sbin/pwrstat -test

- name: Wait 15 seconds for test to finish
  wait_for:
    timeout: 15

- name: Print UPS status and test results (check stdout)
  command: /usr/sbin/pwrstat -status
