---
- name: Conduct a UPS test
  command: /usr/sbin/pwrstat -test

# Wait for test to finish
- pause:
  seconds: 15

- name: Print UPS status and test results (check stdout)
  command: /usr/sbin/pwrstat -status
