---
- name: Update cache
  apt:
    update_cache: yes
    
- name: Upgrade apps where available
  apt:
    upgrade: full
    
- name: Clean up and remove old stuff
  apt:
    autoclean: yes
    autoremove: yes
