---
  - name: Check for active downloads
    find:
      paths: '/mnt/storage/MiscData/Downloads/inprog'
      pattern: '*.*'
      recurse: yes
    register: filesFound
    
  - debug:
      msg: No downloads in progress. Proceeding with SnapRaid maintenance
    when: filesFound.matched < 1

  - debug:
      msg: Downloading is in progress. SnapRaid will NOT be synced and/or scrubbed!
    when: filesFound.matched > 0

  - name: Sync Array
    command: /usr/bin/snapraid sync
    when: arraysync == "Yes" and filesFound.matched < 1

  - name: Scrub array for parity errors. Looking at 1% of files >20 days old
    command: /usr/bin/snapraid -p 1 -o 20 scrub
    when: arrayscrub == "Yes" and filesFound.matched < 1
